/* Auto-generated by tools/extract_logo.py from captures/live_logo.png.
 * Exact ASCII raster of the bolt silhouette. Do not hand-edit shape. */
window.PDFORCE_BOLT_ASCII = ["                           .%*", "                          -%#:", "                         -@:", "                        =#:", "                     :=#+", "                   =*+=.", "                  %*.", "                 +%", "                .%-", "               =#-", "           .-=++.", "          *+=:.", "        .*-", "       .#-", "      .*=", "    -==.", "  .+-.", ".-=:", "*+"];
